{
  pkgs,
  lib,
  config,
  ...
}:
let
  cfg = config.hm.window-managers.hyprland;
in
{
  imports = [
    ./hyprpolkitagent.nix
    ./hyprpicker.nix
    ./t5610.nix
    ./x230t.nix
  ];

  options.hm.window-managers.hyprland.enable = lib.mkEnableOption "enable hyprland";

  config = lib.mkIf cfg.enable {
    home = {
      packages = [
        # inputs.hyprwayland-scanner.packages."${pkgs.stdenv.hostPlatform.system}".default
        pkgs.wf-recorder
        pkgs.grim
        # pkgs.hyprpolkitagent
        pkgs.slurp
        pkgs.wev
        pkgs.cliphist
      ];

      sessionVariables = {
        NIXOS_OZONE_WL = "1";
        AQ_DRM_DEVICES = "/dev/dri/card1";
      };

      # One-shot seeds for the hand-edited configs below; see the
      # xdg.configFile / hyprpaper comments further down for why they are
      # copied out of the store instead of symlinked into it.
      activation = {
        hyprlandConfigSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          target="$HOME/.config/hypr/hyprland.conf"
          if [[ ! -e "$target" ]]; then
            run mkdir -p $VERBOSE_ARG "$HOME/.config/hypr"
            run cp $VERBOSE_ARG ${./hyprland.conf.seed} "$target"
            run chmod u+w $VERBOSE_ARG "$target"
          fi
        '';

        hyprlandLuaSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          target="$HOME/.config/hypr/hyprland.lua"
          if [[ ! -e "$target" ]]; then
            run mkdir -p $VERBOSE_ARG "$HOME/.config/hypr"
            run cp $VERBOSE_ARG ${./hyprland.lua.seed} "$target"
            run chmod u+w $VERBOSE_ARG "$target"
          fi
        '';

        hyprlandKeybindsSeed = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
          target="$HOME/.config/hypr/keybinds.lua"
          if [[ ! -e "$target" ]]; then
            run mkdir -p $VERBOSE_ARG "$HOME/.config/hypr"
            run cp $VERBOSE_ARG ${./keybinds.lua.seed} "$target"
            run chmod u+w $VERBOSE_ARG "$target"
          fi
        '';
      };
    };

    wayland.windowManager.hyprland = {
      enable = true;
      # Pinned rather than left to the stateVersion-dependent default. Both
      # rendered outputs are disabled below, so this only decides which file
      # home-manager *would* declare -- "lua" matches the file actually in use.
      configType = "lua";
      xwayland.enable = true;
      systemd = {
        enable = true;
        # variables = [ "-all" ];
      };
    };

    # Hyprland's config is hand-edited directly rather than regenerated by
    # home-manager every switch. Both candidate outputs are disabled below and
    # seeded once (above) from the last known-good rendered config, so they
    # start out real and mutable instead of read-only Nix-store symlinks:
    # ~/.config/hypr/hyprland.lua (the live config, with keybinds split into a
    # sibling keybinds.lua it require()s) and hyprland.conf (the pre-lua one).
    #
    # Because nothing here reaches disk, this module no longer sets `settings`
    # or `extraConfig` at all -- the previous contents were dead code and have
    # been removed. The .seed files are the record of what they rendered to.
    # Edit ~/.config/hypr/hyprland.lua and keybinds.lua directly instead.
    xdg.configFile."hypr/hyprland.conf".enable = lib.mkForce false;
    xdg.configFile."hypr/hyprland.lua".enable = lib.mkForce false;

    # Same story for hyprpaper: stop Stylix/home-manager from writing
    # ~/.config/hypr/hyprpaper.conf at all. Left inert on purpose (no seed) -
    # set it up by hand if/when you want hyprpaper managing the wallpaper.
    services.hyprpaper.enable = lib.mkForce false;
  };
}
